language: "perl"

services:
  - mysql

perl:
  - "5.14"
  - "5.12"
  - "5.26"

env:
  - COVERALLS=true  DB=mysql
  
sudo: false
  
addons:
  apt:
    packages:
    - unzip

before_install:
  - git clone --depth 1 https://github.com/Ensembl/ensembl-git-tools.git
  - export PATH=$PATH:$PWD/ensembl-git-tools/bin
  - export ENSEMBL_BRANCH=master
  - export SECONDARY_BRANCH=main
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH"
  - if [[ $TRAVIS_BRANCH =~ ^release\/[0-9]+$ ]]; then export ENSEMBL_BRANCH=$TRAVIS_BRANCH; export SECONDARY_BRANCH=$TRAVIS_BRANCH; fi
  - echo "ENSEMBL_BRANCH=$ENSEMBL_BRANCH"
  - echo "SECONDARY_BRANCH=$SECONDARY_BRANCH"
  - git-ensembl --clone --branch $ENSEMBL_BRANCH --secondary_branch $SECONDARY_BRANCH --depth 1 ensembl
  - git-ensembl --clone --branch $ENSEMBL_BRANCH --secondary_branch $SECONDARY_BRANCH --depth 1 ensembl-test
  - git-ensembl --clone --branch $ENSEMBL_BRANCH --secondary_branch $SECONDARY_BRANCH --depth 1 ensembl-taxonomy
  - git-ensembl --clone --branch $ENSEMBL_BRANCH --secondary_branch $SECONDARY_BRANCH --depth 1 ensembl-compara
  - git-ensembl --clone --branch $ENSEMBL_BRANCH --secondary_branch $SECONDARY_BRANCH --depth 1 ensembl-variation
  - git clone --branch version/2.5 --depth 1 https://github.com/Ensembl/ensembl-hive.git
  - git clone --branch release-1-6-924 --depth 1 https://github.com/bioperl/bioperl-live.git


install:
    - cpanm -v --installdeps --with-recommends --notest --cpanfile ensembl/cpanfile .
    - export PERL5LIB=$PERL5LIB:$PWD/bioperl-live
    - cpanm -v --installdeps --notest .
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm -n DBD::SQLite
    - cp travisci/MultiTestDB.conf.travisci.mysql  modules/t/MultiTestDB.conf.mysql
    - cp travisci/MultiTestDB.conf.travisci.SQLite modules/t/MultiTestDB.conf.SQLite
    - mysql -u root -h localhost -e 'GRANT ALL PRIVILEGES ON *.* TO "travis"@"%"'

script: "./travisci/harness.sh"

matrix:
  exclude:
  - perl: '5.12'
    env: COVERALLS=false DB=mysql
  - perl: '5.12'
    env: COVERALLS=true  DB=mysql
  - perl: '5.14'
    env: COVERALLS=false DB=mysql
  - perl: '5.14'
    env: COVERALLS=true  DB=mysql
  - perl: '5.26'
    env: COVERALLS=false DB=sqlite
  - perl: '5.26'
    env: COVERALLS=false DB=mysql

notifications:
  email:
    on_success: always
    on_failure: always
