language: "perl"

perl:
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.26"

env:
  - COVERALLS=true  DB=mysql
  
sudo: false
  
addons:
  apt:
    packages:
    - unzip

before_install:
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-test.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-taxonomy.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-compara.git
    - git clone --branch master --depth 1 https://github.com/Ensembl/ensembl-variation.git
    - git clone --branch version/2.3 --depth 1 https://github.com/Ensembl/ensembl-hive.git
    - wget https://github.com/bioperl/bioperl-live/archive/bioperl-release-1-2-3.zip
    - unzip bioperl-release-1-2-3.zip


install:
    - cpanm -n Devel::Cover::Report::Coveralls
    - cpanm -n DBD::SQLite
    - cpanm -n Log::Log4perl
    - cpanm -n Config::IniFiles
    - cpanm -n JSON
    - cp travisci/MultiTestDB.conf.travisci.mysql  modules/t/MultiTestDB.conf.mysql
    - cp travisci/MultiTestDB.conf.travisci.SQLite modules/t/MultiTestDB.conf.SQLite
    - cd ensembl && cpanm -v --installdeps .
    - cd -

script: "./travisci/harness.sh"

# Get the matrix to only build coveralls support when on 5.10
matrix:
  exclude:
    - perl: "5.10"
      env: COVERALLS=false DB=mysql
    - perl: "5.12"
      env: COVERALLS=false DB=sqlite
    - perl: "5.12"
      env: COVERALLS=true  DB=mysql
    - perl: "5.14"
      env: COVERALLS=false DB=sqlite
    - perl: "5.14"
      env: COVERALLS=true  DB=mysql

notifications:
  email:
    on_success: always
    on_failure: always
